# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.DateField(verbose_name='Datum van publicatie / media optreden.')),
                ('tijd', models.TimeField(blank=True, null=True, verbose_name='Tijdstip.')),
                ('omschrijving', models.TextField(default='', verbose_name='Korte omschrijving.')),
            ],
        ),
    ]
